### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by danielswe88** [ljfranklin/k8s-pi#3]
Hi!

First of all thank you for putting this guide together!

Secondly... I am trying to use some parts of this guide for my own home network / home lab.

I have a unifi USG, two AP Pro, one ESXi machine and some no-name switches. I have everything set up.

One of my ESXi machines is a Mac Pro 2010 which has two network interfaces. I have set up those like this:
Eth1: Through switch which is in the end plugged into LAN1 on USG.
Eth2: Directly to LAN2

On the ESXi machine I have created three virtual ubuntu 18 guests (one to be K8 master and two to be K8 workers / slaves). I have configured so that they use the second network interface.

Everything works good. My K8 cluster lives inside 192.168.2.X and the rest of my home network lives in 192.168.1.X such as AP's apple TV:s, phones, laptops etc. Actually I am not sure how I got the K8 machines into the 192.168.2.X network, was it because of the second ethernet cable into LAN2 or was it because I tagged the LAN2 network (192.168.2.X) with a vlan tag? Anyway... it works as I want it.

Now it comes to your guide. What I am mostly interested in is having metal lb as load balancers and beeing able to route load balanced into my cluster at home from cloud flare, so that I can host some hobby API's / websites.

I read in your guide that you putted your network in the opposite way from what I did. You putted your cluster at LAN1 and the rest at LAN2. Since I have everything configured nicely right now I don't want to reconfigure everything at home regarding AP's and stuff. I quickly tried yesterday and it was a mess, nothing worked, so I switched back LAN1 and LAN2 ports as how they were when it worked.

Can I use the current setup I have and add BGP routing inside LAN2 network?

Thanks in advance and sorry for hijacking an issue with my question.
/Daniel

**Comment by ljfranklin** [comment]
@danielswe88 everything should work fine with the cluster on LAN2. I gave a bit of an explanation [here](https://github.com/ljfranklin/k8s-pi#bgp-mode-recommended), but the main gotcha with using your router as a BGP load balancer is that other machines within the same subnet as the k8s cluster won't be able to use the LB addresses. I'm forgetting the exact technical explanation but machines in different subnets route everything through the routing table where BGP kicks in, while machines within the same subnet use ARP(?) to route by MAC address without hitting the routing table.

So as long as the k8s cluster lives in one LAN and all the clients live in the other LAN or outside your network you should be fine.

**Comment by danielswe88** [comment]
Ah, perfect! Thank you very much!

Is it okay if I come back with more questions down the road?

Or do you want to get contacted in another way? I guess you want to close this issue now?

Thanks again!

**Comment by ljfranklin** [comment]
If you have any more questions specific to the setup instructions I've shared I'll try and answer them here. For more general questions about k8s I'd try asking in community sites like stackexchange or the k8s slack. Good luck with your setup!
